# Pandas Practice Answers (15 Solutions)

In [2]:
# Q1
import pandas as pd
import numpy as np
df=pd.DataFrame({'Marks':[90,np.nan,85]})
df.fillna(0)

   Marks
0   90.0
1    0.0
2   85.0

In [ ]:
# Q2
df=pd.DataFrame({'Marks':[90,np.nan,85]})
df['Marks']=df['Marks'].fillna(df['Marks'].mean())
df

In [3]:
# Q3
df=pd.DataFrame({'Marks':[90,np.nan,85]})
df.ffill()

   Marks
0   90.0
1   90.0
2   85.0

In [ ]:
# Q4
df=pd.DataFrame({'Name':['Krish',None],'Marks':[90,80]})
df.dropna()

In [ ]:
# Q5
df=pd.DataFrame({'Name':['Krish','Raj'],'Marks':[90,None]})
df.dropna(subset=['Marks'])

In [ ]:
# Q6
df=pd.DataFrame({'Department':['IT','HR','IT'],'Salary':[50000,40000,60000]})
df.groupby('Department')['Salary'].mean()

In [ ]:
# Q7
df.groupby('Department')['Salary'].sum()

In [ ]:
# Q8
df.groupby('Department')['Salary'].count()

In [ ]:
# Q9
df=pd.DataFrame({'Marks':[80,90,70]})
df['Marks']=df['Marks'].apply(lambda x:x+5)
df

In [ ]:
# Q10
df=pd.DataFrame({'Marks':[95,82,65]})
df['Grade']=df['Marks'].apply(lambda x:'A' if x>=90 else ('B' if x>=75 else 'C'))
df

In [ ]:
# Q11
import numpy as np
df=pd.DataFrame({'Name':['Krish',None],'Marks':[90,np.nan]})
df['Marks']=df['Marks'].fillna(df['Marks'].mean())
df=df.dropna(subset=['Name'])
df

In [ ]:
# Q12
df=pd.DataFrame({'Department':['IT','HR','IT'],'Salary':[50000,40000,60000]})
df.groupby('Department')['Salary'].agg(['sum','mean','max','min'])

In [ ]:
# Q13
df=pd.DataFrame({'Math':[80,90],'Science':[85,95]})
df['Total']=df.apply(lambda row:row['Math']+row['Science'],axis=1)
df

In [ ]:
# Q14
df=pd.DataFrame({'Name':['Krish'],'Marks':[90]})
df.to_csv('students.csv',index=False)

In [ ]:
# Q15
import pandas as pd
import numpy as np
df=pd.DataFrame({'Name':['Krish','Raj',None],'Department':['IT','IT','HR'],'Marks':[90,np.nan,75]})
df['Marks']=df['Marks'].fillna(df['Marks'].mean())
df=df.dropna(subset=['Name'])
df['Result']=df['Marks'].apply(lambda x:'Pass' if x>=35 else 'Fail')
report=df.groupby('Department')['Marks'].mean()
df.to_csv('final_report.csv',index=False)
print(report)