# Pandas Practice Questions

## Question 1

Create a DataFrame with missing values and replace them with 0 using fillna().

In [4]:
import numpy as np
import pandas as pd
df=pd.DataFrame({
    "name" : ["krish",np.nan,"raj"],
    "mark" : [50,60,np.nan]
})
print(df)
print("\n",df.fillna(0))

    name  mark
0  krish  50.0
1    NaN  60.0
2    raj   NaN

     name  mark
0  krish  50.0
1      0  60.0
2    raj   0.0

## Question 2

Replace missing marks with the column mean.

In [9]:
print(df)
df['mark']=df['mark'].fillna(df['mark'].mean())
print(df)

    name  mark
0  krish  50.0
1    NaN  60.0
2    raj  55.0
    name  mark
0  krish  50.0
1    NaN  60.0
2    raj  55.0

## Question 3

Use forward fill (ffill) to fill missing values.

In [ ]:
df=pd.DataFrame({'name' : ['krish',np.nan,'raj'],'mark' : [50,np.nan,60]
})
print(df.ffill())
print(df.bfill())

    name  mark
0  krish  50.0
1  krish  50.0
2    raj  60.0

    name  mark
0  krish  50.0
1    raj  60.0
2    raj  60.0

## Question 4

Remove all rows containing missing values using dropna().

In [24]:
df.dropna()

    name  mark
0  krish  50.0
2    raj  60.0

## Question 5

Remove rows where Marks is missing.

In [26]:
df.dropna(subset=['mark'])

    name  mark
0  krish  50.0
2    raj  60.0

## Question 6

Find average salary department-wise using groupby().

In [39]:
df=pd.DataFrame({
    "name":["krish","yash","meet","ayush","mirav"],
    "age":[20,34,40,30,23],
    "department":["IT","IT","Management","Management","HR"],
    "salary":[30000,45000,35000,23000,43000]
})
print(df.groupby('department')['salary'].mean())

department
HR            43000.0
IT            37500.0
Management    29000.0
Name: salary, dtype: float64

## Question 7

Find total salary department-wise using groupby().

In [40]:
print(df.groupby('department')['salary'].sum())

department
HR            43000
IT            75000
Management    58000
Name: salary, dtype: int64

## Question 8

Count employees in each department using groupby().

In [42]:
print(df.groupby('department')['name'].count())

department
HR            1
IT            2
Management    2
Name: name, dtype: int64

## Question 9

Add 5 bonus marks using apply().

In [48]:
df=pd.DataFrame({
    "name" : ["krish","ayush","raj"],
    "mark" : [80,60,90]
})
print(df['mark'].apply(lambda x:x+5))

0    85
1    65
2    95
Name: mark, dtype: int64

## Question 10

Create a Grade column using apply().

In [57]:
df=pd.DataFrame({"mark":[60,70,50,90,89,95]})
df['grade']=df['mark'].apply(lambda x: 'A' if x>=90 else 'B' if x>=80 else 'c' if x>=60 else 'D')
print(df)

   mark grade
0    60     c
1    70     c
2    50     D
3    90     A
4    89     B
5    95     A

## Question 11

Use fillna() and dropna() together on a dataset.

In [66]:
df=pd.DataFrame({
    "name" : ["krish",None,"raj"],
    "mark" : [80,60,np.nan]
})
df['mark']=df['mark'].fillna(df["mark"].mean())
print(df,"\n")
df=df.dropna(subset=["name"])
print(df)

    name  mark
0  krish  80.0
1    NaN  60.0
2    raj  70.0

    name  mark
0  krish  80.0
2    raj  70.0

## Question 12

Calculate sum, mean, max, and min using groupby().agg().

In [69]:
df=pd.DataFrame({
    "name":["krish","yash","meet","ayush","mirav"],
    "age":[20,34,40,30,23],
    "department":["IT","IT","Management","Management","HR"],
    "salary":[30000,45000,35000,23000,43000]
})
print(df.groupby('department')['salary'].agg(["sum","mean","max","min"]))

              sum     mean    max    min
department
HR          43000  43000.0  43000  43000
IT          75000  37500.0  45000  30000
Management  58000  29000.0  35000  23000

## Question 13

Calculate Total Marks using row-wise apply().

In [70]:
df = pd.DataFrame({
    'Math': [80, 90, 70],
    'Science': [85, 75, 95],
    'English': [90, 80, 85]
})

print(df)

   Math  Science  English
0    80       85       90
1    90       75       80
2    70       95       85

## Question 14

Export a DataFrame using to_csv().

In [71]:
df=pd.DataFrame({
    "name":["krish","yash","meet","ayush","mirav"],
    "age":[20,34,40,30,23],
    "department":["IT","IT","Management","Management","HR"],
    "salary":[30000,45000,35000,23000,43000]
})
df.to_csv('emp.csv',index=False)

## Question 15

Create a mini project using fillna(), dropna(), groupby(), apply(), and to_csv().

In [100]:
df=pd.DataFrame({
    "name":["krish","yash",None,"ayush","mirav"],
    "age":[20,34,40,None,23],
    "department":["IT","IT","Management","Management","HR"],
    "salary":[30000,45000,np.nan,23000,43000]
})
df['age']=df["age"].fillna(round(df["age"].mean()))
df['salary']=df["salary"].fillna(df["salary"].mean())
df=df.dropna(subset=['name'])
b=df.groupby('department')["salary"].mean()
df['bonus']=5000
df['total_salary']=df["salary"].apply(lambda x:x+5000)
print(df)
print("\n",b)
df.to_csv('emp1.csv',index=False)

    name   age  department   salary  bonus  total_salary
0  krish  20.0          IT  30000.0   5000       35000.0
1   yash  34.0          IT  45000.0   5000       50000.0
3  ayush  29.0  Management  23000.0   5000       28000.0
4  mirav  23.0          HR  43000.0   5000       48000.0

 department
HR            43000.0
IT            37500.0
Management    23000.0
Name: salary, dtype: float64