# Pandas Read Data Practice (Question + Answer Format)

## Question
1. Read `students.csv` and display all records.

In [2]:
import pandas as pd
df=pd.read_csv('stud.csv')
df

   StudentID   Name  Age  Gender Course  Marks       City
0        101   Amit   20    Male    BCA     85     Rajkot
1        102  Priya   21  Female  BScIT     92  Ahmedabad
2        103  Rahul   22    Male   BCom     78      Surat
3        104   Neha   20  Female  BScIT     88     Rajkot
4        105  Karan   23    Male    BCA     67   Vadodara
5        106  Pooja   21  Female  BScIT     95  Ahmedabad
6        107  Vikas   22    Male    BCA     73      Surat
7        108   Riya   20  Female   BCom     81     Rajkot
8        109  Arjun   21    Male  BScIT     89   Vadodara
9        110  Sneha   22  Female    BCA     91  Ahmedabad

## Question
2. Display only the `name` and `age` columns from `students.csv`.

In [5]:
df=pd.read_csv('stud.csv',usecols=['Name','Age'])
df

    Name  Age
0   Amit   20
1  Priya   21
2  Rahul   22
3   Neha   20
4  Karan   23
5  Pooja   21
6  Vikas   22
7   Riya   20
8  Arjun   21
9  Sneha   22

## Question
3. Read the first 3 rows from a CSV file.

In [7]:
df=pd.read_csv('stud.csv',nrows=3)
df

   StudentID   Name  Age  Gender Course  Marks       City
0        101   Amit   20    Male    BCA     85     Rajkot
1        102  Priya   21  Female  BScIT     92  Ahmedabad
2        103  Rahul   22    Male   BCom     78      Surat

## Question
4. Read `students.xlsx` and display the data.

In [9]:
df=pd.read_excel('students.xlsx')
df

   id   name  age       city
0   1  Krish   20     Rajkot
1   2  Rahul   21  Ahmedabad
2   3  Priya   19      Surat

## Question
5. Read only `Sheet2` from an Excel file.

In [12]:
df=pd.read_excel('students.xlsx', sheet_name="Sheet2")
df

   id  course  marks
0   1  Python     85
1   2  Pandas     90
2   3   NumPy     88

## Question
6. Read `students.json` and display all records.

In [14]:
df=pd.read_json('students.json')
df

   id   name  age       city
0   1  Krish   20     Rajkot
1   2  Rahul   21  Ahmedabad
2   3  Priya   19      Surat

## Question
7. Read the first HTML table from `students.html`.

In [22]:
import pandas as pd

url = "https://www.w3schools.com/html/html_tables.asp"

tables = pd.read_html(url)

tables[0]

                        Company           Contact  Country
0           Alfreds Futterkiste      Maria Anders  Germany
1    Centro comercial Moctezuma   Francisco Chang   Mexico
2                  Ernst Handel     Roland Mendel  Austria
3                Island Trading     Helen Bennett       UK
4  Laughing Bacchus Winecellars   Yoshi Tannamuri   Canada
5  Magazzini Alimentari Riuniti  Giovanni Rovelli    Italy

## Question
8. Save a DataFrame to a Pickle file named `students.pkl`.

In [25]:
df=pd.read_csv('stud.csv')
df.to_pickle('student.pkl')

## Question
9. Read data from `students.pkl` and display it.

In [26]:
df=pd.read_pickle('student.pkl')
df

   StudentID   Name  Age  Gender Course  Marks       City
0        101   Amit   20    Male    BCA     85     Rajkot
1        102  Priya   21  Female  BScIT     92  Ahmedabad
2        103  Rahul   22    Male   BCom     78      Surat
3        104   Neha   20  Female  BScIT     88     Rajkot
4        105  Karan   23    Male    BCA     67   Vadodara
5        106  Pooja   21  Female  BScIT     95  Ahmedabad
6        107  Vikas   22    Male    BCA     73      Surat
7        108   Riya   20  Female   BCom     81     Rajkot
8        109  Arjun   21    Male  BScIT     89   Vadodara
9        110  Sneha   22  Female    BCA     91  Ahmedabad

## Question
10. Compare the shape (rows, columns) of data loaded from CSV and JSON files.

In [30]:
csv_sp=pd.read_csv('stud.csv')
json_sp=pd.read_json('students.json')
print("csv :",csv_sp.shape)
print("json :",json_sp.shape)

csv : (10, 7)
json : (3, 4)